src/gui/components/GraphComponent.h
- Prevents points from being dragged outside axis bounds.
- When mouse position is outside the bounds of one axis but not the other, points can still be moved along the other axis.
Closes #45
=> fix(gui): prevent points being moved outside axis bounds

src/Interpolator.h
- Disables `-Wmissing-prototypes` from external spline library.
Closes #65
=> build: disable missing prototype warnings in external spline library

src/Application.cpp, src/Application.h, src/CommandManager.h, src/gui/CMakeLists.txt, src/gui/components/GraphComponent.h, src/gui/components/MainComponent.h, src/gui/components/TorqueMapComponent.h, src/gui/menubar/MenuBar.cpp, src/gui/menubar/MenuBar.h, src/gui/windows/MainWindow.cpp, src/gui/windows/MainWindow.h
- Creates the boilerplate for the menu bar including an application command manager.
- Fixes some build issues (missing `#pragma once` and a circular dependency). 
Closes #58
=> feat(gui): create menu bar outline

CMakeLists.txt, src/Application.cpp, src/Application.h, src/gui/CMakeLists.txt, src/gui/menubar/MenuBar.cpp, src/gui/menubar/MenuBar.h, src/gui/windows/AboutWindow.cpp, src/gui/windows/AboutWindow.h, src/gui/windows/MainWindow.cpp, src/gui/windows/MainWindow.h
- Creates an 'About' window showing the application name and version information.
- The window is accessed through the menu bar.
- `GIT_COMMIT_HASH` string is now available as a pre-processor definition.
Closes #67
=> feat(gui): create 'About' window

.vscode/launch.json, CMakeLists.txt
- 'VCU-GUI' -> 'VCU GUI'.
- The CMake target is still `VCU-GUI`.
Closes #69
=> build: remove dash from app title

src/gui/components/GraphComponent.h
- The interpolated graph curve is now cached until points on the curve move.
- If the graph component is resized, an affine transform is applied to the path to resize it to the component bounds.
Closes #80
=> perf(gui): add caching of the interpolated graph curve

.gitignore, .vscode/c_cpp_properties.json, src/ConfigurationValueTree.cpp, src/ConfigurationValueTree.h, src/gui/components/MainComponent.cpp, src/gui/components/MainComponent.h
- Remove the code export functionality. This was broken and will be replaced with a system for directly communicating with the VCU.
=> chore: clean up for next development cycle

.trunk/config/.clang-format, src/Interpolator.h
- Adds definition of `M_PI` when building on Windows.
- This is needed by `spline.h`.
- Build should now work with no errors on Windows.
Closes #96
=> build(windows): fix missing definition of `M_PI`

.trunk/config/.clang-format, .trunk/trunk.yaml, src/Application.cpp, src/ConfigurationValueTree.cpp, src/ConfigurationValueTree.h, src/Interpolator.h, src/gui/appearance/LookAndFeel.cpp, src/gui/appearance/LookAndFeel.h, src/gui/components/GraphComponent.h, src/gui/components/InverterConfigComponent.cpp, src/gui/components/InverterConfigComponent.h, src/gui/components/MainComponent.cpp, src/gui/components/MainComponent.h, src/gui/components/TabbedComponent.cpp, src/gui/components/TorqueMapComponent.cpp, src/gui/components/TorqueMapComponent.h, src/gui/menubar/MenuBar.cpp, src/gui/menubar/MenuBar.h, src/gui/utility/PointComparator.h, src/gui/windows/AboutWindow.cpp, src/gui/windows/AboutWindow.h, src/gui/windows/MainWindow.cpp, src/gui/windows/MainWindow.h, src/utility/linspace.h
- Updates `clang-format` config to reduce line limit to 80 cols.
- Applies new formatting.
- General cleanup of in-source documentation format.
=> chore: update formatting

src/CommandManager.h, src/gui/menubar/MenuBar.cpp, src/gui/menubar/MenuBar.h, src/gui/windows/MainWindow.cpp, src/gui/windows/MainWindow.h
- Re-implements the config load/save functionality which used to be buttons in the main component.
- Fixes an issue where the torque map graph didn't sync with the config value tree when the deadzone was moved.
Closes #108
=> feat(gui): add config load/save to menu bar

CMakeLists.txt, src/config/CMakeLists.txt, src/config/ConfigParameter.cpp, src/config/ConfigParameter.h, src/config/ConfigParameterGroup.cpp, src/config/ConfigParameterGroup.h, src/config/ConfigParameterRanged.h
- Initial attempt at some classes for defining configuration parameters.
- Based on a mix of `juce::Value` and `juce::AudioProcessorParameter`.
- Needs some more work once the container for the data model is better defined.
=> feat(config): outline for config parameter classes

CMakeLists.txt, src/Interpolator.h
- Added global define in CMakeList to remove build error for M_PI in spline.h
Better fix for #96
=> build(windows): add global _USE_MATH_DEFINE to root CMakeLists

src/ConfigurationValueTree.cpp, src/gui/components/MainComponent.cpp, src/gui/components/config/GraphComponent.h, src/utility/Interpolator.h
- Moves `Interpolator` class into utilities folder.
- It was in the `utility` namespace, so it makes sense for it to be there.
=> refactor(utils): move Interpolator into utility folder

.trunk/trunk.yaml
- Update trunk to v1.0.1 (finally out of beta!).
Closes #124
=> chore(trunk): bump to v1.0.1

CMakeLists.txt
- Modified CMakeList to avoid symlink of compile commands database to root repo on Windows
=> build(windows): don't symlink compile commands to repo root on Windows

.vscode/c_cpp_properties.json, .vscode/launch.json
Edited launch.json file and tested debugger. Needed to install the Windows SDK separately and explicitly choose Debugging tools for windows. TODO: update the Dev Setup.md with this information.
Update the docs folder for windows set up.
Edited the c_cpp_properties.json file. Intellisense works but was unable to solve issue regarding compile_commands.json not found. @t-bre looked through your suggestions but as I have no experience doing this or working with MSVC I was unable to figure it out, if you do have another solution in mind let me know
Closes #115
=> chore(vscode): set up build/run/debug on Windows

src/Application.cpp, src/Application.h, src/gui/windows/MainWindow.cpp
- Previously non-existent menu bar added to top of `MainWindow` on Linux and Windows platforms.
- Fixes an issue where the `sufst::LookAndFeel` instance was deleted but still referenced by some components. Weirdly, this has never happened before and only seemed to become a problem when the menu bar was added to the main window.
Closes #109
=> fix(gui): add menu bar to main window on Linux and Windows

CMakeLists.txt, src/CommandManager.h, src/gui/menubar/MenuBar.cpp, src/gui/menubar/MenuBar.h
- Adds a 'Help' menu to the menu bar.
- This provides access to the 'About' window on Windows and Linux.
- On macOS, the 'About' window is intentionally accessible both through the help menu and the "Apple menu." 
- Also includes a link to this GitHub repo in the help menu.
Fixes #140 
Looks like this on macOS:
=> feat(gui): add 'Help' menu to menu bar

.vscode/launch.json
- Adds explicit specification of target architecture when running `lldb` debugger on macOS.
- This prevents the warning `"Warning: Debuggee TargetArchitecture not detected, assuming x86_64."` when running on an ARM Mac.
Closes #141
=> chore(vscode): specify `lldb` target architecture on macOS

src/gui/appearance/LookAndFeel.cpp, src/gui/components/config/GraphComponent.h, src/gui/windows/AboutWindow.cpp
- Fixed C4244 warning through CMake target_compile_options command
Closes #145
=> build(windows): fix C4244 int to float conversion warning

CMakeLists.txt
- Remove -`D flag` from `-DGIT_COMMIT_HASH=\"${GIT_COMMIT_HASH}\"` for MSVC to display hash in 'About' window on Windows
Closes #144
=> fix(gui): commit hash not shown in 'About' window on Windows
